PipelineConfig:
  properties:
    add_review:
      allOf:
      - $ref: 'AddReviewAction'
      description: An action to add a review to the PR with an optional comment
      title: Add Review
    apply_labels:
      allOf:
      - $ref: 'ApplyLabelsAction'
      description: An action to apply labels to a matching pull request. If no action
        is specified, the pipeline will simply analyse the change and add a comment
        to the PR. Currently the only supported action.
      title: Apply Labels
    id:
      description: An optional unique ID for this config, will be used to identify
        the config in logs/status checks.
      example: label-prod-prs
      maxLength: 200
      minLength: 1
      title: Id
      type: string
    when:
      allOf:
      - $ref: 'When'
      default:
        repo:
        - '*'
      description: A set of filters compared against an incoming changeto decide when
        to run this pipeline.
      title: When
  title: PipelineConfig
  type: object
